on: push

jobs:
  mysql-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          echo "SHOW DATABASES;" | mysql -h127.0.0.1 -uroot -proot
