name: Build Node App

on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Node.js version
        run: node --version

      - name: Show NPM version
        run: npm --version

      - name: Run app.js
        run: node app.js
