on: push

jobs:
  test-python:
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - run: python --version
      - run: python -c "print('Hola crayola desde Python en un contenedor')"
